trigger:
  branches:
    include:
      - main

variables:
  imageName: 'apache-app'
  acrName: 'testingcr'
  acrLoginServer: 'testingcr.azurecr.io'
  tag: '$(Build.BuildId)'
  imageFullName: '$(acrLoginServer)/$(imageName):$(tag)'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker Image
    jobs:
      - job: BuildAndPush
        pool:
          name: minato
        steps:
          - checkout: self

          - script: |
              sudo apt-get update
              sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
              sudo apt-get update
              sudo apt-get install -y docker-ce docker-ce-cli containerd.io
              sudo systemctl start docker
              sudo systemctl enable docker
              docker --version
            displayName: 'Install Docker'

          - task: Docker@2
            displayName: Build and Push Image to ACR
            inputs:
              containerRegistry: 'acr_pipeline'  
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)

  - stage: Deploy
    displayName: Deploy to Kubernetes
    dependsOn: BuildAndPush
    jobs:
      - job: DeployToK8s
        displayName: Deploy to AKS
        pool:
          name: minato  
        steps:
          - task: KubernetesManifest@0
            displayName: Deploy to AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: 'yuno'
              namespace: default
              manifests: |
                $(Build.SourcesDirectory)/deployment.yaml
                $(Build.SourcesDirectory)/service.yaml
              containers: |
                $(imageFullName)
