trigger:
  branches:
    include:
      - main

stages:
  - stage: Deploy
    jobs:
      - job: DeployToK8s
        displayName: Deploy to Kubernetes
        pool:
          name: minato
        steps:
          - script: |
              echo "Debugging files:"
              ls -l $(Build.SourcesDirectory)
            displayName: "List Source Directory"

          - task: Kubernetes@1
            displayName: Deploy to cluster
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'yuno'
              namespace: default
              command: apply
              useConfigurationFile: true
              filePaths: |
                $(Build.SourcesDirectory)/deployment.yaml
                $(Build.SourcesDirectory)/service.yaml
