trigger:
  branches:
    include:
      - main

stages:
  - stage: Deploy
    jobs:
      - job: DeployToK8s
        displayName: Deploy to Kubernetes
        pool:
          name: minato
        steps:
          - task: Kubernetes@1
            displayName: Deploy to cluster
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'yuno'
              namespace: default
              command: apply
              useConfigurationFile: true
              configuration: |
                deployment.yaml
                service.yaml

